# Generated by Django 4.2.5 on 2023-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.URLField(blank=True)),
                ('lot_size', models.PositiveIntegerField()),
                ('min_qty', models.PositiveIntegerField()),
                ('isin', models.CharField(max_length=20)),
                ('special_comment', models.TextField(blank=True)),
                ('sell_price_rupees', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
